# Use an official PostgreSQL image as the base
FROM postgres:latest

# Optionally set environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=r00TRoot

# Optionally expose the PostgreSQL port
EXPOSE 5432

# Command to run the PostgreSQL server
CMD ["postgres"]
